name: Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "Version of the Docker image to be released"
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        run: echo ${{ secrets.SPECMATIC_DOCKER_HUB_TOKEN }} | docker login -u ${{ vars.SPECMATIC_DOCKER_HUB_USERNAME }} --password-stdin

      - uses: actions/checkout@v4

      - name: Download semver cli
        if: runner.os != 'Windows'
        shell: bash
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: Validate the given version number
        run: semver validate ${{ inputs.version_number }}

      - name: Build and Publish
        run: docker buildx build --push --platform=linux/amd64,linux/arm64 -t specmatic/specmatic-mcp:${{ inputs.version_number }} -t specmatic/specmatic-mcp:latest .

      - name: Tag the repo
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.SPECMATIC_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git tag ${{ inputs.version_number }}
          git push origin ${{ inputs.version_number }}
